apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipelinerun-helloworld-
  namespace: diploe2-cror
spec:
  serviceAccountName: tekton-sa
  pipelineRef:
    name: pipeline-hello-world
  params:
    - name: your-name
      value: "Cristian Ricardo Ortega Ramírez"
    - name: repo-url
      value: https://github.com/cortegaunam/upload-image-service.git
  workspaces:
    - name: empty-dir
      emptyDir: {}
