apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-trigger-binding-cicd
  namespace: diploe2-cror
spec:
  params:
    - name: repo-url
      value: $(body.repository.clone_url)
    #- name: branch-name
    #  value: main #$(body.repository.default_branch)
    - name: image-name
      value: docker.io/richyortega/proyecto-diplomado:$(body.head_commit.id)
    - name: deploy-name
      value: proyecto-diplomado-cror
