apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-cicd
spec:
  description: |
    This is the pipeline  of the final proyect of Diplomado
    Pipeline works:
    Tasks defined in the pipeline:
      - git-clone: fetching the project git repository as the source
      - buildha: generate the container image and publish to dockerhub
      - deploy: deploy the project in kubernetes
  params:
    - name: repo-url
      type: string
    - name: image-name
      type: string
    - name: deploy-name
      type: string
  workspaces:
    - name: workspace
    - name: dockerconfig
    - name: empty-dir
  tasks:
    - name: fetch-repository
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url # <- this is the git-clone param
          value: $(params.repo-url) # <- a reference to param
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output # <- should be the same as the git-clone task
          workspace: workspace # <- the workspace defined up
    - name: build-and-push-image
      taskRef:
        kind: Task
        name: buildah
      runAfter: # <- the task should start once fetch-repository ends
        - fetch-repository
      params:
        - name: IMAGE
          value: $(params.image-name)
        - name: TLSVERIFY
          value: 'false'
        - name: STORAGE_DRIVER
          value: 'vfs'
      workspaces:
        - name: source
          workspace: workspace
        - name: dockerconfig
          workspace: dockerconfig
    - name: deploy-project
      taskRef:
        kind: Task
        name: kubernetes-actions
      runAfter:
       - build-and-push-image
      params:
        - name: script
          value: |
            kubectl delete deployment $(params.deploy-name)
            kubectl create deployment $(params.deploy-name) --image=$(params.image-name)
            kubectl set env deployment/$(params.deploy-name) --from=configmap/my-config
            echo "----------"
            kubectl get deployment
      workspaces:
        - name: kubeconfig-dir
          workspace: empty-dir
        - name: manifest-dir
          workspace: empty-dir
