apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  APP_PORT: "8085"
  MONGO_URI: "mongodb://admin:admin123@mongodb-service-richyortega:27017/images?authSource=admin"
  MINIO_URL: "http://minio-service-richyortega:9000"
  MINIO_PASS: "miniopass"
  MINIO_BUCKET_NAME: "uploaded-images"
