apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-richyortega
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-richyortega
  template:
    metadata:
      labels:
        app: minio-richyortega
    spec:
      containers:
      - name: minio-container
        image: minio/minio:RELEASE.2024-10-13T13-34-11Z        
        ports:
        - containerPort: 9000
        - containerPort: 9001
        env:
        - name: MINIO_ROOT_USER
          value: miniouser
        - name: MINIO_ROOT_PASSWORD
          value: miniopass
        args: 
          - server
          - /data
          - --console-address
          - ":9001"
