apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyect-richyortega
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proyect-richyortega
  template:
    metadata:
      labels:
        app: proyect-richyortega
    spec:
      containers:
        - name: proyect-container
          image: {{IMAGE_NAME}}:{{NEW_VERSION}}
          ports:
            - containerPort: 8085
          env:
            - name: APP_PORT
              value: '8085'
            - name: MONGO_URI
              value: 'mongodb://admin:admin123@mongodb-service-richyortega:27017/images?authSource=admin'
            - name: MINIO_URL
              value: http://minio-service-richyortega:9000
            - name: MINIO_USER
              value: miniouser
            - name: MINIO_PASSWORD
              value: miniopass
            - name: MINIO_BUCKET_NAME
              value: uploaded-images
