apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-richyortega
spec:
  selector:
    app: mongodb-deploy-richyortega
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: NodePort
