apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: build-and-push-
  namespace: diploe2-cror
spec:
  serviceAccountName: tekton-sa  # Usar el service account
  podTemplate:
    securityContext:
      fsGroup: 65532
  taskSpec:
    params:
      - name: IMAGE_BASE_NAME
        type: string
        default: richyortega/proyecto-diplomado
    workspaces:
      - name: workspace
      - name: docker-credentials
    steps:
      - name: get-git-tag
        image: alpine/git
        script: |
          #!/bin/sh
          cd /workspace/workspace
          git config --global --add safe.directory /workspace/workspace
          git fetch --prune --unshallow
          TAG=$(git describe --tags --always || echo "latest")
          echo "El TAG del repositorio es: $TAG"
          echo $TAG > /workspace/workspace/git-tag.txt

      - name: build-image
        image: quay.io/buildah/stable
        script: |
          #!/bin/sh
          TAG=$(cat /workspace/workspace/git-tag.txt)
          IMAGE_URL="$(params.IMAGE_BASE_NAME):$TAG"
          echo "Creando imagen: $IMAGE_URL"
          buildah build --storage-driver=overlay -t $IMAGE_URL /workspace/workspace/
          echo "Login en DockerHub"
          buildah login -u $(cat /workspace/docker-credentials/username) -p $(cat /workspace/docker-credentials/password) docker.io
          echo "Publicando imagen: $IMAGE_URL"
          buildah push --storage-driver=overlay $IMAGE_URL
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: workspace
    - name: docker-credentials
      secret:
        secretName: basic-user-pass
